:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\Simline2
dotnet build src\Simline2
echo Now, run the following to start the project: dotnet run -p src\Simline2\Simline2.csproj --launch-profile web.
echo.
