/*
 * 登記・供託オンライン申請システムAPI
 *
 *  本リファレンスは登記・供託オンライン申請システムAPIリファレンスとなります。  登記・供託オンライン申請システムAPIを利用することで、オンライン申請、処理状況の確認、公文書取得等を行うことができます。  本リファレンスは「API一覧」と「リクエスト・レスポンス一覧」で構成されており、それぞれ以下の内容を記しています。  ■API一覧      各APIの仕様について記しています。  ■リクエスト・レスポンス一覧      各APIのリクエスト及びレスポンスの構造や各API共通で扱う共通エラーレスポンスの構造を記しています。なお、Exampleの値はSwaggerファイルと異なる表記となる場合がありますので、別途提供するSwaggerファイルをあわせて確認してください。  共通エラーレスポンスは以下の4種類です。詳細についてはリクエスト・レスポンス一覧の内容を確認してください。    ・HTTP403（Forbidden）    ・HTTP404（Not Found）      ・HTTP500（Internal Server Error）      ・HTTP503（Service unavailable）    
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Simline2.Converters;

namespace Simline2.Models
{ 
    /// <summary>
    /// 納付情報暗号化レスポンス
    /// </summary>
    [DataContract]
    public partial class EncryptNofuJohoResponse : IEquatable<EncryptNofuJohoResponse>
    {
        /// <summary>
        /// 暗号化された納付情報
        /// </summary>
        /// <value>暗号化された納付情報</value>
        [DataMember(Name="encryptedNofuJoho", EmitDefaultValue=false)]
        public string EncryptedNofuJoho { get; set; }

        /// <summary>
        /// 納付状況：  - 0 ・・・ 未登録 - 1 ・・・ 未納付 - 2 ・・・ 納付済み - 3 ・・・ 納付期限切れ - 4 ・・・ 納付取消済み 
        /// </summary>
        /// <value>納付状況：  - 0 ・・・ 未登録 - 1 ・・・ 未納付 - 2 ・・・ 納付済み - 3 ・・・ 納付期限切れ - 4 ・・・ 納付取消済み </value>
        [RegularExpression("/^[0-4]$/")]
        [DataMember(Name="nofuJokyo", EmitDefaultValue=false)]
        public int? NofuJokyo { get; set; }

        /// <summary>
        /// 納付日時
        /// </summary>
        /// <value>納付日時</value>
        [DataMember(Name="nofuNichiji", EmitDefaultValue=false)]
        public DateTime? NofuNichiji { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EncryptNofuJohoResponse {\n");
            sb.Append("  EncryptedNofuJoho: ").Append(EncryptedNofuJoho).Append("\n");
            sb.Append("  NofuJokyo: ").Append(NofuJokyo).Append("\n");
            sb.Append("  NofuNichiji: ").Append(NofuNichiji).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EncryptNofuJohoResponse)obj);
        }

        /// <summary>
        /// Returns true if EncryptNofuJohoResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of EncryptNofuJohoResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EncryptNofuJohoResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    EncryptedNofuJoho == other.EncryptedNofuJoho ||
                    EncryptedNofuJoho != null &&
                    EncryptedNofuJoho.Equals(other.EncryptedNofuJoho)
                ) && 
                (
                    NofuJokyo == other.NofuJokyo ||
                    NofuJokyo != null &&
                    NofuJokyo.Equals(other.NofuJokyo)
                ) && 
                (
                    NofuNichiji == other.NofuNichiji ||
                    NofuNichiji != null &&
                    NofuNichiji.Equals(other.NofuNichiji)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (EncryptedNofuJoho != null)
                    hashCode = hashCode * 59 + EncryptedNofuJoho.GetHashCode();
                    if (NofuJokyo != null)
                    hashCode = hashCode * 59 + NofuJokyo.GetHashCode();
                    if (NofuNichiji != null)
                    hashCode = hashCode * 59 + NofuNichiji.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EncryptNofuJohoResponse left, EncryptNofuJohoResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EncryptNofuJohoResponse left, EncryptNofuJohoResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
