/*
 * 登記・供託オンライン申請システムAPI
 *
 *  本リファレンスは登記・供託オンライン申請システムAPIリファレンスとなります。  登記・供託オンライン申請システムAPIを利用することで、オンライン申請、処理状況の確認、公文書取得等を行うことができます。  本リファレンスは「API一覧」と「リクエスト・レスポンス一覧」で構成されており、それぞれ以下の内容を記しています。  ■API一覧      各APIの仕様について記しています。  ■リクエスト・レスポンス一覧      各APIのリクエスト及びレスポンスの構造や各API共通で扱う共通エラーレスポンスの構造を記しています。なお、Exampleの値はSwaggerファイルと異なる表記となる場合がありますので、別途提供するSwaggerファイルをあわせて確認してください。  共通エラーレスポンスは以下の4種類です。詳細についてはリクエスト・レスポンス一覧の内容を確認してください。    ・HTTP403（Forbidden）    ・HTTP404（Not Found）      ・HTTP500（Internal Server Error）      ・HTTP503（Service unavailable）    
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Simline2.Converters;

namespace Simline2.Models
{ 
    /// <summary>
    /// 受領通知取得レスポンス
    /// </summary>
    [DataContract]
    public partial class JuryoJohoResponse : IEquatable<JuryoJohoResponse>
    {
        /// <summary>
        /// 受領通知の内容。HTML形式だが、body要素の中身のみ。
        /// </summary>
        /// <value>受領通知の内容。HTML形式だが、body要素の中身のみ。</value>
        [Required]
        [DataMember(Name="juryoTsuchi", EmitDefaultValue=false)]
        public string JuryoTsuchi { get; set; }

        /// <summary>
        /// 商業・法人区分：  - 1 ・・・ 商業 - 2 ・・・ 法人 - 9 ・・・ その他 
        /// </summary>
        /// <value>商業・法人区分：  - 1 ・・・ 商業 - 2 ・・・ 法人 - 9 ・・・ その他 </value>
        [Required]
        [RegularExpression("^[129]$")]
        [DataMember(Name="shogyoHojinKubun", EmitDefaultValue=false)]
        public string ShogyoHojinKubun { get; set; }

        /// <summary>
        /// 受付番号
        /// </summary>
        /// <value>受付番号</value>
        [Required]
        [DataMember(Name="uketsukeBangos", EmitDefaultValue=false)]
        public List<JuryoJohoResponseUketsukeBangos> UketsukeBangos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JuryoJohoResponse {\n");
            sb.Append("  JuryoTsuchi: ").Append(JuryoTsuchi).Append("\n");
            sb.Append("  ShogyoHojinKubun: ").Append(ShogyoHojinKubun).Append("\n");
            sb.Append("  UketsukeBangos: ").Append(UketsukeBangos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((JuryoJohoResponse)obj);
        }

        /// <summary>
        /// Returns true if JuryoJohoResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of JuryoJohoResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JuryoJohoResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    JuryoTsuchi == other.JuryoTsuchi ||
                    JuryoTsuchi != null &&
                    JuryoTsuchi.Equals(other.JuryoTsuchi)
                ) && 
                (
                    ShogyoHojinKubun == other.ShogyoHojinKubun ||
                    ShogyoHojinKubun != null &&
                    ShogyoHojinKubun.Equals(other.ShogyoHojinKubun)
                ) && 
                (
                    UketsukeBangos == other.UketsukeBangos ||
                    UketsukeBangos != null &&
                    other.UketsukeBangos != null &&
                    UketsukeBangos.SequenceEqual(other.UketsukeBangos)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (JuryoTsuchi != null)
                    hashCode = hashCode * 59 + JuryoTsuchi.GetHashCode();
                    if (ShogyoHojinKubun != null)
                    hashCode = hashCode * 59 + ShogyoHojinKubun.GetHashCode();
                    if (UketsukeBangos != null)
                    hashCode = hashCode * 59 + UketsukeBangos.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(JuryoJohoResponse left, JuryoJohoResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(JuryoJohoResponse left, JuryoJohoResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
