/*
 * 登記・供託オンライン申請システムAPI
 *
 *  本リファレンスは登記・供託オンライン申請システムAPIリファレンスとなります。  登記・供託オンライン申請システムAPIを利用することで、オンライン申請、処理状況の確認、公文書取得等を行うことができます。  本リファレンスは「API一覧」と「リクエスト・レスポンス一覧」で構成されており、それぞれ以下の内容を記しています。  ■API一覧      各APIの仕様について記しています。  ■リクエスト・レスポンス一覧      各APIのリクエスト及びレスポンスの構造や各API共通で扱う共通エラーレスポンスの構造を記しています。なお、Exampleの値はSwaggerファイルと異なる表記となる場合がありますので、別途提供するSwaggerファイルをあわせて確認してください。  共通エラーレスポンスは以下の4種類です。詳細についてはリクエスト・レスポンス一覧の内容を確認してください。    ・HTTP403（Forbidden）    ・HTTP404（Not Found）      ・HTTP500（Internal Server Error）      ・HTTP503（Service unavailable）    
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Simline2.Converters;

namespace Simline2.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class JuryoJohoResponseUketsukeBangos : IEquatable<JuryoJohoResponseUketsukeBangos>
    {
        /// <summary>
        /// 枝番１
        /// </summary>
        /// <value>枝番１</value>
        [Required]
        [RegularExpression("^[0-9]{2}$")]
        [DataMember(Name="edaban1", EmitDefaultValue=false)]
        public string Edaban1 { get; set; }

        /// <summary>
        /// 枝番２
        /// </summary>
        /// <value>枝番２</value>
        [Required]
        [RegularExpression("^[0-9]{2}$")]
        [DataMember(Name="edaban2", EmitDefaultValue=false)]
        public string Edaban2 { get; set; }

        /// <summary>
        /// 本番
        /// </summary>
        /// <value>本番</value>
        [Required]
        [RegularExpression("^[0-9]{6}$")]
        [DataMember(Name="homban", EmitDefaultValue=false)]
        public string Homban { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JuryoJohoResponseUketsukeBangos {\n");
            sb.Append("  Edaban1: ").Append(Edaban1).Append("\n");
            sb.Append("  Edaban2: ").Append(Edaban2).Append("\n");
            sb.Append("  Homban: ").Append(Homban).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((JuryoJohoResponseUketsukeBangos)obj);
        }

        /// <summary>
        /// Returns true if JuryoJohoResponseUketsukeBangos instances are equal
        /// </summary>
        /// <param name="other">Instance of JuryoJohoResponseUketsukeBangos to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JuryoJohoResponseUketsukeBangos other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Edaban1 == other.Edaban1 ||
                    Edaban1 != null &&
                    Edaban1.Equals(other.Edaban1)
                ) && 
                (
                    Edaban2 == other.Edaban2 ||
                    Edaban2 != null &&
                    Edaban2.Equals(other.Edaban2)
                ) && 
                (
                    Homban == other.Homban ||
                    Homban != null &&
                    Homban.Equals(other.Homban)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Edaban1 != null)
                    hashCode = hashCode * 59 + Edaban1.GetHashCode();
                    if (Edaban2 != null)
                    hashCode = hashCode * 59 + Edaban2.GetHashCode();
                    if (Homban != null)
                    hashCode = hashCode * 59 + Homban.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(JuryoJohoResponseUketsukeBangos left, JuryoJohoResponseUketsukeBangos right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(JuryoJohoResponseUketsukeBangos left, JuryoJohoResponseUketsukeBangos right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
