/*
 * 登記・供託オンライン申請システムAPI
 *
 *  本リファレンスは登記・供託オンライン申請システムAPIリファレンスとなります。  登記・供託オンライン申請システムAPIを利用することで、オンライン申請、処理状況の確認、公文書取得等を行うことができます。  本リファレンスは「API一覧」と「リクエスト・レスポンス一覧」で構成されており、それぞれ以下の内容を記しています。  ■API一覧      各APIの仕様について記しています。  ■リクエスト・レスポンス一覧      各APIのリクエスト及びレスポンスの構造や各API共通で扱う共通エラーレスポンスの構造を記しています。なお、Exampleの値はSwaggerファイルと異なる表記となる場合がありますので、別途提供するSwaggerファイルをあわせて確認してください。  共通エラーレスポンスは以下の4種類です。詳細についてはリクエスト・レスポンス一覧の内容を確認してください。    ・HTTP403（Forbidden）    ・HTTP404（Not Found）      ・HTTP500（Internal Server Error）      ・HTTP503（Service unavailable）    
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Simline2.Converters;

namespace Simline2.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class NofuJohoResponseResults : IEquatable<NofuJohoResponseResults>
    {
        /// <summary>
        /// 確認番号
        /// </summary>
        /// <value>確認番号</value>
        [RegularExpression("/^[0-9]{6}$/")]
        [DataMember(Name="kakuninBango", EmitDefaultValue=false)]
        public string KakuninBango { get; set; }

        /// <summary>
        /// 納付番号 (数字16桁＋英字(空白含む)4桁)
        /// </summary>
        /// <value>納付番号 (数字16桁＋英字(空白含む)4桁)</value>
        [RegularExpression("/^[0-9]{16}[a-zA-Z ]{4}$/")]
        [DataMember(Name="nofuBango", EmitDefaultValue=false)]
        public string NofuBango { get; set; }

        /// <summary>
        /// 納付額
        /// </summary>
        /// <value>納付額</value>
        [DataMember(Name="nofuGaku", EmitDefaultValue=false)]
        public long NofuGaku { get; set; }

        /// <summary>
        /// 納付情報発行日時
        /// </summary>
        /// <value>納付情報発行日時</value>
        [DataMember(Name="nofuJohoHakkoNichiji", EmitDefaultValue=false)]
        public DateTime NofuJohoHakkoNichiji { get; set; }

        /// <summary>
        /// 納付状況：  - 0 ・・・ 未登録 - 1 ・・・ 未納付 - 2 ・・・ 納付済み - 3 ・・・ 納付期限切れ - 4 ・・・ 納付取消済み 
        /// </summary>
        /// <value>納付状況：  - 0 ・・・ 未登録 - 1 ・・・ 未納付 - 2 ・・・ 納付済み - 3 ・・・ 納付期限切れ - 4 ・・・ 納付取消済み </value>
        [Required]
        [RegularExpression("/^[0-4]$/")]
        [DataMember(Name="nofuJokyo", EmitDefaultValue=false)]
        public int NofuJokyo { get; set; }

        /// <summary>
        /// 納付期間最終年月日
        /// </summary>
        /// <value>納付期間最終年月日</value>
        [DataMember(Name="nofuKikanSaishuNengappi", EmitDefaultValue=false)]
        public DateTime NofuKikanSaishuNengappi { get; set; }

        /// <summary>
        /// 納付済み通知日時。  供託申請の場合、利用者が納付を行った時点の領収年月日を返却する（時分秒は「00:00:00」で返却する）  その他申請の場合、歳入金電子納付システムから領収済み通知を受けた日時を返却する（利用者が納付を行った時点の日時ではないことに留意すること）  ※納付済みでない場合、納付済み通知日時は返却しない。 
        /// </summary>
        /// <value>納付済み通知日時。  供託申請の場合、利用者が納付を行った時点の領収年月日を返却する（時分秒は「00:00:00」で返却する）  その他申請の場合、歳入金電子納付システムから領収済み通知を受けた日時を返却する（利用者が納付を行った時点の日時ではないことに留意すること）  ※納付済みでない場合、納付済み通知日時は返却しない。 </value>
        [DataMember(Name="nofuNichiji", EmitDefaultValue=false)]
        public DateTime NofuNichiji { get; set; }

        /// <summary>
        /// 収納機関番号
        /// </summary>
        /// <value>収納機関番号</value>
        [RegularExpression("^[0-9]{5}$")]
        [DataMember(Name="shunoKikanBango", EmitDefaultValue=false)]
        public string ShunoKikanBango { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NofuJohoResponseResults {\n");
            sb.Append("  KakuninBango: ").Append(KakuninBango).Append("\n");
            sb.Append("  NofuBango: ").Append(NofuBango).Append("\n");
            sb.Append("  NofuGaku: ").Append(NofuGaku).Append("\n");
            sb.Append("  NofuJohoHakkoNichiji: ").Append(NofuJohoHakkoNichiji).Append("\n");
            sb.Append("  NofuJokyo: ").Append(NofuJokyo).Append("\n");
            sb.Append("  NofuKikanSaishuNengappi: ").Append(NofuKikanSaishuNengappi).Append("\n");
            sb.Append("  NofuNichiji: ").Append(NofuNichiji).Append("\n");
            sb.Append("  ShunoKikanBango: ").Append(ShunoKikanBango).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((NofuJohoResponseResults)obj);
        }

        /// <summary>
        /// Returns true if NofuJohoResponseResults instances are equal
        /// </summary>
        /// <param name="other">Instance of NofuJohoResponseResults to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NofuJohoResponseResults other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    KakuninBango == other.KakuninBango ||
                    KakuninBango != null &&
                    KakuninBango.Equals(other.KakuninBango)
                ) && 
                (
                    NofuBango == other.NofuBango ||
                    NofuBango != null &&
                    NofuBango.Equals(other.NofuBango)
                ) && 
                (
                    NofuGaku == other.NofuGaku ||
                    
                    NofuGaku.Equals(other.NofuGaku)
                ) && 
                (
                    NofuJohoHakkoNichiji == other.NofuJohoHakkoNichiji ||
                    NofuJohoHakkoNichiji != null &&
                    NofuJohoHakkoNichiji.Equals(other.NofuJohoHakkoNichiji)
                ) && 
                (
                    NofuJokyo == other.NofuJokyo ||
                    
                    NofuJokyo.Equals(other.NofuJokyo)
                ) && 
                (
                    NofuKikanSaishuNengappi == other.NofuKikanSaishuNengappi ||
                    NofuKikanSaishuNengappi != null &&
                    NofuKikanSaishuNengappi.Equals(other.NofuKikanSaishuNengappi)
                ) && 
                (
                    NofuNichiji == other.NofuNichiji ||
                    NofuNichiji != null &&
                    NofuNichiji.Equals(other.NofuNichiji)
                ) && 
                (
                    ShunoKikanBango == other.ShunoKikanBango ||
                    ShunoKikanBango != null &&
                    ShunoKikanBango.Equals(other.ShunoKikanBango)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (KakuninBango != null)
                    hashCode = hashCode * 59 + KakuninBango.GetHashCode();
                    if (NofuBango != null)
                    hashCode = hashCode * 59 + NofuBango.GetHashCode();
                    
                    hashCode = hashCode * 59 + NofuGaku.GetHashCode();
                    if (NofuJohoHakkoNichiji != null)
                    hashCode = hashCode * 59 + NofuJohoHakkoNichiji.GetHashCode();
                    
                    hashCode = hashCode * 59 + NofuJokyo.GetHashCode();
                    if (NofuKikanSaishuNengappi != null)
                    hashCode = hashCode * 59 + NofuKikanSaishuNengappi.GetHashCode();
                    if (NofuNichiji != null)
                    hashCode = hashCode * 59 + NofuNichiji.GetHashCode();
                    if (ShunoKikanBango != null)
                    hashCode = hashCode * 59 + ShunoKikanBango.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(NofuJohoResponseResults left, NofuJohoResponseResults right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(NofuJohoResponseResults left, NofuJohoResponseResults right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
